name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: nutwente    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.*'                 # set this to the .NET Core version to use

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Restore dependencies
        run: dotnet restore Ordina.StichtingNuTwente/Ordina.StichtingNuTwente.sln
      
      - name: Build with dotnet
        run: dotnet build Ordina.StichtingNuTwente/ --configuration Release

      - name: Test
        run: dotnet test Ordina.StichtingNuTwente/ --no-restore --verbosity normal

      - name: dotnet publish
        run: dotnet publish Ordina.StichtingNuTwente/ -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

  
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: './appsettings.json'
        env:
          Connectionstrings.NuTwente: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_MAILFROM_ADDRESS: ${{ secrets.SENDGRID_MAILFROM_ADDRESS }}
          SENDGRID_MAILFROM_NAME: ${{ secrets.SENDGRID_MAILFROM_NAME }}
          EMAILADRESSB: ${{ secrets.SENDGRID_MAILTO_B }}
          EMAILADRESSO: ${{ secrets.SENDGRID_MAILTO_O }}
          EMAILADRESSR: ${{ secrets.SENDGRID_MAILTO_R }}
          EMAILADRESST: ${{ secrets.SENDGRID_MAILTO_T }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
